export const LeftNavBarData = [
    {
        title: 'Laptop',
        path: '/products/Laptop',
        category:'Laptop',
        iconPath:'/images/laptop.png',
        icon: <img width="25px" height="25px" src="/images/laptop.png" alt="laptop" />,
        cName: 'nav-text',
    },
    {
        title: 'Desktop Workstations',
        path: '/products/Desktop Workstations',
        category:'Desktop Workstations',
        iconPath:'/images/workstation.png',
        icon: <img width="25px" height="25px" src="/images/workstation.png" alt="workstation" />,
        cName: 'nav-text',
    },
    {
        title: 'Gaming PCs',
        path: '/products/Gaming PCs',
        category: 'Gaming PCs',
        iconPath:'/images/gamingPC.png',
        icon: <img width="25px" height="25px" src="/images/gamingpc.png" alt="gamingPC" />,
        cName: 'nav-text',
    },
    {
        title: 'Budget PCs',
        path: '/products/Budget PCs',
        category: 'Budget PCs',
        iconPath:'/images/pc.png',
        icon: <img width="25px" height="25px" src="/images/pc.png" alt="pc" />,
        cName: 'nav-text',
    },
    {
        title: 'Processors',
        path: '/products/Processors',
        category: 'Processors',
        iconPath:'/images/processor.png',
        icon: <img width="25px" height="25px" src="/images/processor.png" alt="processor" />,
        cName: 'nav-text',
    },
    {
        title: 'MotherBoards',
        path: '/products/MotherBoards',
        category: 'MotherBoards',
        iconPath:'/images/motherboard.png',
        icon: <img width="25px" height="25px" src="/images/motherboard.png" alt="motherboard" />,
        cName: 'nav-text',
    },
    {
        title: 'Memory (RAM)s',
        path: '/products/Memory (RAM)s',
        category: 'Memory (RAM)s',
        iconPath:'/images/ram.png',
        icon: <img width="25px" height="25px" src="/images/ram.png" alt="ram" />,
        cName: 'nav-text',
    },
    {
        title: 'Graphic Cards',
        path: '/products/Graphic Cards',
        category: 'Graphic Cards',
        iconPath:'/images/gpu.png',
        icon: <img width="25px" height="25px" src="/images/gpu.png" alt="gpu" />,
        cName: 'nav-text',
    },
    {
        title: 'Storages',
        path: '/products/Storages',
        category: 'Storages',
        iconPath:'/images/storage.png',
        icon: <img width="25px" height="25px" src="/images/storage.png" alt="storage" />,
        cName: 'nav-text',
    },
    {
        title: 'Power Supplies',
        path: '/products/Power Supplies',
        category: 'Power Supplies',
        iconPath:'/images/power.png',
        icon: <img width="25px" height="25px" src="/images/power.png" alt="power" />,
        cName: 'nav-text',
    },
    {
        title: 'Monitors',
        path: '/products/Monitors',
        category: 'Monitors',
        iconPath:'/images/monitor.png',
        icon: <img width="25px" height="25px" src="/images/monitor.png" alt="monitor" />,
        cName: 'nav-text',
    },
    {
        title: 'Accessories',
        path: '/products/Accessories',
        category: 'Accessories',
        iconPath:'/images/keyboard.png',
        icon: <img width="25px" height="25px" src="/images/keyboard.png" alt="keyboard" />,
        cName: 'nav-text',
    },
    {
        title: 'Software',
        path: '/products/Software',
        category: 'Software',
        iconPath:'/images/software.png',
        icon: <img width="25px" height="25px" src="/images/software.png" alt="software" />,
        cName: 'nav-text',
    },
    {
        title: 'Casings',
        path: '/products/Casings',
        category: 'Casings',
        iconPath:'/images/casing.png',
        icon: <img width="25px" height="25px" src="/images/casing.png" alt="casing" />,
        cName: 'nav-text',
    },
    
]