export const AdminLeftNavBarData = [
    {
        title: 'Overview',
        path: '/admin',
        iconPath:'/images/icons8-chart-96.png',
        icon: <img width="25px" height="25px" src="/images/icons8-chart-96.png" alt="overview" />,
        cName: 'nav-text',
    },
    {
        title: 'Items',
        path: '/admin/viewItems',
        iconPath:'/images/icons8-product-90.png',
        icon: <img width="25px" height="25px" src="/images/icons8-product-90.png" alt="Items" />,
        cName: 'nav-text',
    },
    {
        title: 'Delivery',
        path: '/admin/viewDeliveries',
        iconPath:'/images/icons8-delivery-100.png',
        icon: <img width="25px" height="25px" src="/images/icons8-delivery-100.png" alt="delivery" />,
        cName: 'nav-text',
    },
    {
        title: 'Users',
        path: '/admin/viewUsers',
        iconPath:'/images/icons8-users-90.png',
        icon: <img width="25px" height="25px" src="/images/icons8-users-90.png" alt="users" />,
        cName: 'nav-text',
    },
    {
        title: 'Settings',
        path: '/admin/settings',
        iconPath:'/images/icons8-settings-384.png',
        icon: <img width="25px" height="25px" src="/images/icons8-settings-384.png" alt="settings" />,
        cName: 'nav-text',
    },
    {
        title: 'Reports',
        path: '/admin/reports',
        iconPath:'/images/icons8-report.png',
        icon: <img width="25px" height="25px" src="/images/icons8-report.png" alt="report" />,
        cName: 'nav-text',
    },
    {
        title: 'Logout',
        path: '/admin/reports',
        iconPath:'/images/pc.png',
        icon: <img width="25px" height="25px" src="/images/pc.png" alt="report" />,
        cName: 'nav-text',
    },
]