export const LeftNavBarData = [
    {
        title: 'Laptop',
        path: '/products/laptop',
        category:'laptop',
        iconPath:'/images/laptop.png',
        icon: <img width="25px" height="25px" src="/images/laptop.png" alt="laptop" />,
        cName: 'nav-text',
    },
    {
        title: 'Desktop Workstations',
        path: '/products/desktop_workstations',
        category:'desktop_workstations',
        iconPath:'/images/workstation.png',
        icon: <img width="25px" height="25px" src="/images/workstation.png" alt="workstation" />,
        cName: 'nav-text',
    },
    {
        title: 'Gaming PCs',
        path: '/products/gaming_pcs',
        category: 'gaming_pcs',
        iconPath:'/images/gamingPC.png',
        icon: <img width="25px" height="25px" src="/images/gamingPC.png" alt="gamingPC" />,
        cName: 'nav-text',
    },
    {
        title: 'Budget PCs',
        path: '/products/budget_pcs',
        category: 'budget_pcs',
        iconPath:'/images/pc.png',
        icon: <img width="25px" height="25px" src="/images/pc.png" alt="pc" />,
        cName: 'nav-text',
    },
    {
        title: 'Processors',
        path: '/products/processors',
        category: 'processors',
        iconPath:'/images/processor.png',
        icon: <img width="25px" height="25px" src="/images/processor.png" alt="processor" />,
        cName: 'nav-text',
    },
    {
        title: 'MotherBoards',
        path: '/products/motherBoards',
        category: 'motherBoards',
        iconPath:'/images/motherboard.png',
        icon: <img width="25px" height="25px" src="/images/motherboard.png" alt="motherboard" />,
        cName: 'nav-text',
    },
    {
        title: 'Memory (RAM)s',
        path: '/products/memory',
        category: 'memory',
        iconPath:'/images/ram.png',
        icon: <img width="25px" height="25px" src="/images/ram.png" alt="ram" />,
        cName: 'nav-text',
    },
    {
        title: 'Graphic Cards',
        path: '/products/graphic_cards',
        category: 'graphic_cards',
        iconPath:'/images/gpu.png',
        icon: <img width="25px" height="25px" src="/images/gpu.png" alt="gpu" />,
        cName: 'nav-text',
    },
    {
        title: 'Storages',
        path: '/products/storages',
        category: 'storages',
        iconPath:'/images/storage.png',
        icon: <img width="25px" height="25px" src="/images/storage.png" alt="storage" />,
        cName: 'nav-text',
    },
    {
        title: 'Power Supplies',
        path: '/products/power_supplies',
        category: 'power_supplies',
        iconPath:'/images/power.png',
        icon: <img width="25px" height="25px" src="/images/power.png" alt="power" />,
        cName: 'nav-text',
    },
    {
        title: 'Monitors',
        path: '/products/monitors',
        category: 'monitors',
        iconPath:'/images/monitor.png',
        icon: <img width="25px" height="25px" src="/images/monitor.png" alt="monitor" />,
        cName: 'nav-text',
    },
    {
        title: 'Accessories',
        path: '/products/accessories',
        category: 'accessories',
        iconPath:'/images/keyboard.png',
        icon: <img width="25px" height="25px" src="/images/keyboard.png" alt="keyboard" />,
        cName: 'nav-text',
    },
    {
        title: 'Software',
        path: '/products/software',
        category: 'software',
        iconPath:'/images/software.png',
        icon: <img width="25px" height="25px" src="/images/software.png" alt="software" />,
        cName: 'nav-text',
    },
    {
        title: 'Casings',
        path: '/products/casings',
        category: 'casings',
        iconPath:'/images/casing.png',
        icon: <img width="25px" height="25px" src="/images/casing.png" alt="casing" />,
        cName: 'nav-text',
    },
    
]